on:
  push:

name: Release

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y musl-tools busybox-static
      - uses: actions/cache@v2
        with:
          path: |
            target/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=aarch64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --target=aarch64-unknown-linux-musl
