on:
  push:
    tags: ['*']

name: Release

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y musl-tools busybox-static
      - run: sudo apt-get install -y gcc-aarch64-linux-gnu
        if: matrix.target == 'aarch64-unknown-linux-musl'
      - run: rustup target add ${{ matrix.target }}
      - uses: actions/cache@v2
        with:
          path: |
            target/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
          key: "${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}"
      - run: cargo build --release --all-features --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: musl-executable-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/magicpak
      - run: cargo test --release --all-features --target=${{ matrix.target }}
        if: matrix.target == 'x86_64-unknown-linux-musl'  # TODO: test aarch64
  build_docker_images:
    name: Build and push docker images
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Free up disk space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: musl-executable-x86_64-unknown-linux-musl
      - run: mkdir -p dist/amd64 && mv ./magicpak ./dist/amd64/magicpak
      - uses: actions/download-artifact@v2
        with:
          name: musl-executable-aarch64-unknown-linux-musl
      - run: mkdir -p dist/arm64 && mv ./magicpak ./dist/arm64/magicpak
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/setup-buildx-action@v1
      - run: docker buildx bake --push --set '*.cache-from=type=gha' --set '*.cache-to=type=gha,mode=max'
        env:
          BIN_DIR: "./dist"
          VERSION: "1.3.1"
  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: build_docker_images
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: musl-executable-${{ matrix.target }}
      - run: mv magicpak magicpak-${{ matrix.target }}
      - uses: softprops/action-gh-release@v1
        with:
          files: magicpak-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload:
    name: Upload to crates.io
    runs-on: ubuntu-22.04
    needs: release
    steps:
      - uses: actions/checkout@v2
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
