on:
  push:
    tags: ['*']

name: Release

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y musl-tools
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=x86_64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --target=x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v2
        with:
          name: musl-executable
          path: ./target/x86_64-unknown-linux-musl/release/magicpak
  build_docker_images:
    name: Build and push docker images
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: musl-executable
      - run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: PUSH_IMAGES=true ./dockerfile/build.sh ./magicpak
  test_examples:
    name: Test examples
    runs-on: ubuntu-20.04
    needs: build_docker_images
    steps:
      - uses: actions/checkout@v2
      - name: Build examples
        run: |
          for example in ./example/*; do
            docker build "$example"
          done
  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: test_examples
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: musl-executable
      - run: mv magicpak magicpak-x86_64-unknown-linux-musl
      - uses: softprops/action-gh-release@v1
        with:
          files: magicpak-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload:
    name: Upload to crates.io
    runs-on: ubuntu-20.04
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
