on:
  push:
    tags: ['*']

name: Release

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y musl-tools busybox-static
      - run: sudo apt-get install -y gcc-aarch64-linux-gnu
        if: matrix.target == 'aarch64-unknown-linux-musl'
      - uses: actions/cache@v2
        with:
          path: |
            target/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
          key: "${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --target=${{ matrix.target }}
        if: matrix.target == 'x86_64-unknown-linux-musl'  # TODO: test aarch64
      - uses: actions/upload-artifact@v2
        with:
          name: musl-executable-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/magicpak
  build_docker_images:
    name: Build and push docker images
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: musl-executable-x86_64-unknown-linux-musl
      - run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/setup-buildx-action@v1
      - run: ./dockerfile/build.sh ./magicpak
        env:
          PUSH_IMAGES: true
          DOCKER_BUILD: "docker buildx build --load --cache-from type=gha --cache-to type=gha,mode=max"
  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: build_docker_images
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: musl-executable-${{ matrix.target }}
      - run: mv magicpak magicpak-${{ matrix.target }}
      - uses: softprops/action-gh-release@v1
        with:
          files: magicpak-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload:
    name: Upload to crates.io
    runs-on: ubuntu-20.04
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
