on: push

name: Test and Lint

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true
      - run: sudo apt-get install -y musl-tools
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --target=${{ matrix.target }}
  test_examples:
    name: Test examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          for example in ./example/*; do
            docker build "$example"
          done
  build_docker_images:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: ./dockerfile/build.sh
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
